import ContentChoose from "./buttons/ContentChoose";
import '../../public/mainBody.css'
import HomePost from "./contentPost/HomePost";
export default function MainBody({ className }) {
  return (
    <div className={`${className} relative h-screen`}>
      <div className="content-trans">
        <ContentChoose />
      </div>
      <div className="overflow-auto">
        <HomePost></HomePost>
        <h1>hhh</h1>
        <p className="text-red-600">More content goes here...</p><br />
        <p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br />
        <p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br />
        <p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br /><p className="text-red-600">More content goes here...</p><br />
      </div>
    </div>
  );
}
